#!/bin/sh -ue
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# This script runs the tests of the project.
#
# See [README.md] for an explanation of this and how CI should use it.

# * verify - runs all tests including integration tests
./mvnw -nsu verify
